#! /usr/bin/php
<?php
// Gausah ganti CopyRight kalo lu mau di hargai
// Yang ganti copyright mandul 7turunan fix ea
// By Mr.Cakil - 99Syndicate
print "[ =========================================================================== ]\n";
	print " --> admin page finder v1 <--\n";
	print " -==Coded by Mr. Cakil 99syndicate ==-\n";
	print " -= greetz: 99Syndicate - hacker patah hati =-\n";
	print "--> usage: php namafile.php http://lusuka.coli start <--\n";
	print "[ =========================================================================== ]\n\n";
$cakil = array();
function run($array,$kentod){
	for($i = 0;$i < count($array); $i++){
		$url = $kentod."/".urlencode($array[$i]);
		$url = str_replace("%0A","",$url);
		$url = str_replace("%2F","/",$url);
		$headers = exec("curl -A \"Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_3 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8J2 Safari/6533.18.5\" -s -o /dev/null -I -w \"%{http_code}\" $url");
                $headers = str_replace("%","",$headers);
		echo $url." [".$headers."]\n";
		if($headers == "200") 
		{
			$cakil[] = $url;		
		}
	}
	print_r($cakil);
}
if(isset($_SERVER['argv'][1]) and isset($_SERVER['argv'][2])){
	$act2 = $_SERVER['argv'][2];
	$kentod = $_SERVER['argv'][1];
		$link = array(
	"php"	 => array('admin',
'adm',
'/concluido/',
'/concluido/loading.php',
'admincp',
'admcp',
'admin123',
'cp',
'modcp',
'moderatorcp',
'adminarea',
'admins',
'cpanel',
'controlpanel',
'admin1.php',
'admin1.php',
'admin1.html',
'admin2.php',
'adminweb/',
'adminweb/index.php',
'admini/',
'administrator-login/',
'admin-login/',
'Admin/',
'login-page/',
'page-login/',
'admin-page/',
'page-admin/',
'login-2/',
'adminarea/',
'crm/',
'paneladmin/',
'log/',
'login1/',
'admin@web/',
'admin@web/index.php',
'administrasi/index.php',
'login_area/index.php',
'masterweb/',
'rahasia/',
'terminal/',
'admin-web/',
'terminal/',
'monitor/',
'portal/',
'portaladmin/',
'terasadmin/',
'adminkpu/',
'admindinkes/',
'jdih/',
'manager/',
'data/',
'webmin/',
'myadmin/',
'leb/',
'w3bc0ntr0l/',
'adminkoster/',
'panel/',
'web-admin/index.php',
'index.php/adminweb/',
'backup/login/',
'backup/adminweb/',
'author/',
'admin.web/',
'v1/login/',
'v2/admin/',
'v2/admin/',
'adminn/',
'staff/',
'atur/',
'loginpage/',
'adminarea/',
'formadmin/',
'admin/index.php',
'index.php/login',
'member/login.php',
'memberarea/',
'wp-admin/',
'wp-login.php',
'default.php',
'robots.txt',
'administrator/',
'administrator/index.php',
'logon/index.php',
'administrasi/index.php',
'webmaster/index.php',
'webmaster/',
'adminsd/',
'adminsmk/',
'admin123/',
'admin123/login.php',
'123/',
'redtubby/',
'@dmin/',
'@dminweb/',
'adminsekolah/',
'loginsmp/',
'superadmin/',
'webadmin/',
'menu/',
'menuweb/',
'menuadmin/',
'masterweb/',
'adminsma/',
'adminsmp/',
'paneladmin/',
'adminpanel/',
'control/',
'portaladmin/',
'adminnimda/',
'loginsma/',
'operator/index.php',
'logout.php',
'file/',
'xpanel/',
'xadmin/', 
'download/',
'files/',
'1admin/',
'2admin/',
'web/',
'loggin/',
'adm/',
'c_admin/',
'c_panel/',
'controladmin/',
'control/',
'html/',
'admin2.html',
'

'dashboard/',

'adm/',
'config/',

'configure/',

'_file-manager/php/connector.php',


'loggin/',
'admin/',
'admin.php',
'admin.html',
'admin/cp.php',
'admin/cp.html',
'cp.php',
'cp.html',


'adminhotel/',
'config/',

'usr/',
'user/',
'loginuser/',
'logincms/',
'backupadmin/',
'backup/',
'b4ckup/',
'adminhost/',
'admincms/',
'min/',
'in/',

'userlogin/',



'admin12/',
'dasboard/',
'administrator/',
'administrator.php',
'administrator.html',
'login.php',
'login.html',
'modelsearch/login.php',
'moderator.php',
'moderator.html',
'moderator/',
'moderator/login.html',
'moderator/admin.php',
'moderator/admin.html',
'moderator/',
'account.php',
'account.html',
'controlpanel/',
'controlpanel.php',
'controlpanel.html',
'admincontrol.php',
'admincontrol.html',
'adminpanel.php',
'adminpanel.html',
'admin1.asp',
'admin2.asp',
'admin/account.asp',
'admin/index.asp',
'admin/login.asp',
'admin/home.asp',
'admin/controlpanel.asp',
'admin.asp',
'admin/cp.asp',
'cp.asp',
'administrator/index.asp',
'administrator/login.asp',
'administrator/account.asp',
'administrator.asp',
'login.asp',
'modelsearch/login.asp',
'moderator.asp',
'moderator/login.asp',
'moderator/admin.asp',
'account.asp',
'controlpanel.asp',
'admincontrol.asp',
'adminpanel.asp',
'fileadmin/',
'fileadmin.php',
'fileadmin.asp',
'fileadmin.html',
'wpanel',
'wpanel/index.php',
'wpanel/login.php',
'adminpanel',
'adminpanel/index.php',
'adminpanel/login.php',

'sysadmin.php',
'sysadmin.html',
'phpmyadmin/',
'myadmin/',
'sysadmin.asp',
'sysadmin/',

'Server.php',
'Server.html',
'Server.asp',
'Server/',
'wp-admin/',

'webadmin/',
'webadmin.php',
'webadmin.asp',
'webadmin.html',

'admins/',
'admins.php',
'admins.asp',
'admins.html',
'administrivia/',
'Database_Administration/',
'WebAdmin/',
'useradmin/',
'sysadmins/',
'admin1/',

'SysAdmin/',

'sys-admin/',

'panel/',
'cpanel/',
'cPanel/',
'cpanel_file/',


'members/',
'sub-login/',
'wp-login/',
'login1/',
'dir-login/',
'login_db/',
'xlogin/',
'smblogin/',
'UserLogin/',
'login-us/',
'acct_login/',
'admin_area/',


'Super-Admin/',
'AdminTools/',
'cmsadmin/',
'SysAdmin2/',

'adminLogin/',

'admin/admin.php',
'admin_area/admin.php',
'admin_area/',
'siteadmin/login.php',
'siteadmin/index.php',
'siteadmin/login.html',
'admin/admin.html',
'admin_area/index.php',

'admin/admin_login.html',
'admin_login.html',
'panel-administracion/login.html',

'webadmin/login.php',
'admin/admin_login.php',
'admin_login.php',
'admin_area/admin.html',
'pages/admin/admin-login.php',
'admin/admin-login.php',
'admin-login.php',

'admin/home.html',
'pages/admin/admin-login.html',
'admin/admin-login.html',
'admin-login.html',
'admin/adminLogin.html',
'adminLogin.html',
'home.html',
'user.html',

'adm/index.html',
'adm.html',
'user.php',
'panel-administracion/login.php',
'wp-login.php',
'adminLogin.php',
'admin/adminLogin.php',
'home.php',
'adminarea/index.php',
'adminarea/admin.php',
'adminarea/login.php',
'panel-administracion/index.php',
'panel-administracion/admin.php',

'modelsearch/admin.php',
'admincontrol/login.php',
'adm/admloginuser.php',
'admloginuser.php',
'admin2/login.php',
'admin2/index.php',
'adm/index.php',
'adm.php',

'admin/admin.asp',
'admin_area/admin.asp',
'admin_area/login.asp',
'admin_area/index.asp',

'admin/admin-login.asp',
'admin-login.asp',
'user.asp',
'webadmin/index.asp',
'webadmin/admin.asp',
'webadmin/login.asp',
'admin/admin_login.asp',
'admin_login.asp',
'panel-administracion/login.asp',
'adminLogin.asp',
'admin/adminLogin.asp',
'home.asp',
'admloginuser.asp',
'admin2/login.asp',
'admin2/index.asp',
'adm/index.asp',
'adm.asp',
'adm_auth.asp',
'ADMIN/',
'login/',
'cms/',
'administrador/',
'ADMIN/login.php',
'panelc/',
'ADMIN/login.html'),
	);
	switch($act2){
		
		case "start":
			run($link["php"],$kentod);
		break;
		
	
	}
	}

else {
print "[Copyright2017@Mr.Cakil]\n\n";
}
?>